### ISSUE TITLE
Some questions about the grace

### ISSUE THREAD

**Issue by ProHuper** [sands-lab/grace#19]
Hi, I'm curious about why we need the Memory module here. Why it is needed to compensate before compressing and update after compressing.

Also, does grace support local gradient accumulation?
 e.g. when I use topk or dgc compression, it will automatically accumulate those grads that are too small in this round, and reduce them when they are big enough. If so, do I have to control when to use zero_grad to clear the grads?

**Comment by hangxu0304** [comment]
Hi,

The Memory module works exactly like the local gradient accumulation feature you described here. For general compressors, the residual module is sufficient. For a set of particular compressors(e.g. dgc, efsignsgd, powersgd), there is a corresponding module for each of them.

**Comment by ProHuper** [comment]
thx, i'll look deeply into this part
