### ISSUE TITLE
Any plans to port to latest Horovod (0.24) ?

### ISSUE THREAD

**Issue by ASDen** [sands-lab/grace#21]
First thanks for the great effort here, Horovod really needs a good gradient compression library! Today's cloud environments really needs this and this is why the official DDP started also supporting gradient compression algorithms....FP16 is not enough anymore

However, I can see only an old version is supported, any plans / roadmap to port to newer versions ?

Thanks,

**Comment by hangxu0304** [comment]
Hi. Generally, we only plan to support the major versions of Horovod. Is there any specific feature or compatibility issue in Horovod 0.24?

**Comment by ASDen** [comment]
yeah it just doesn't work with 0.24 :) 
Most of this is because a lot has changed in `torch/optimizer.py` in horovod, and currently grace just [copies a modified old version of it](https://github.com/sands-lab/grace/blob/master/update_patch_files.sh), which doesn't work

**Comment by hangxu0304** [comment]
Thanks for letting us know. We are working on a more elegant way to integrate with Horovod. Hopefully, it will ease the compatibility issue. Stay tuned.
