### ISSUE TITLE
The question about QSGD algorithm in the paper

### ISSUE THREAD

**Issue by aonrdbit** [sands-lab/grace#23]
![image](https://user-images.githubusercontent.com/34164349/167646511-5760a605-9498-4687-8994-3a8e3f73b3cf.png)
As shown in the figure.

In the case of s=4, l=3, the probability that I calculate p(i) according to the QSGD algorithm is not 0.2336, but p(i)=0.2336 in the case of l=0. 

But the g(i) corresponding to the probability 0.2336 should be 0 instead of 1/4. This is also in line with the coordinate map below the picture, and the distance from 0.2336 to the endpoint (0) should be shorter. 

Is this understanding correct? I sincerely look forward to your reply!

**Comment by hangxu0304** [comment]
Thanks for pointing out the issue. Actually the results on this figure is correct, but the formula given in the QSGD algorithm in our paper is wrong. Here is the correct one:
<img width="636" alt="image" src="https://user-images.githubusercontent.com/52653060/167695472-ea09cc53-8dd6-4e3b-b36b-1b704cd2938f.png">
