### ISSUE TITLE
GRACE PyTorch Distributed

### ISSUE THREAD

**Issue by vineeths96** [sands-lab/grace#6]
Does the Pytorch Distributed implementation still require Horovod for its working? I see that the communication protocols use Pytorch DDP calls, but there are other function calls such as [broadcast_parameters](https://github.com/sands-lab/grace/blob/bbb127cabbfef0cce477fdc555063abc4d0f0e48/examples/pytorch_mnist.py#L106) and [broadcast_optimizer_state](https://github.com/sands-lab/grace/blob/bbb127cabbfef0cce477fdc555063abc4d0f0e48/examples/pytorch_mnist.py#L107) that still uses Horovod.

**Comment by karatse** [comment]
The Pytorch Distributed implementation does not require Horovod. The example you are looking at is not using DDP. We are updating the examples with a new folder structure, similar to the grace_dl package. Please consider checking [this example](https://github.com/sands-lab/grace/tree/master/examples/dist/CIFAR10-dawndist). As you can see, it uses `init_process_group` to set up the environment. We will include more information on the documentation soon.

**Comment by Yong-gui** [comment]
On my own laptop without GPU, I try to run the Pytorch Distributed example , but it encounter error  "Torch not compiled with CUDA enabled".

**Comment by vineeths96** [comment]
@karatse Thank you, for uploading a new example based on my issue. I really appreciate that. I will definitely check that out.

@Yong-gui I think that is because the example is written for distributed learning with GPUs.

**Comment by Yong-gui** [comment]
I find two places that may need changes for running the example/dist/CIFAR10-dawndist/
1, grace/example/dist/CIFAR10-dawndist/core.py    line 205
change "new_tensor = grc.step(grad)"  to "new_tensor = grc.step(grad,name)"

2, grace/grace_dl/dist/__init__.py line 51
change "return self.send_receive(tensor, name, ctx)"  to "return self.send_receive(tensors_compressed, name, ctx)"

**Comment by vineeths96** [comment]
Normally we would use `DistributedDataParallel` to replicate the models in each GPU. Does this happen in the `build_graph` function in the given example?

**Comment by hangxu0304** [comment]
> Normally we would use `DistributedDataParallel` to replicate the models in each GPU. Does this happen in the `build_graph` function in the given example?

No. We didn't use `DistributedDataParallel ` in that dist example. Embedding GRACE into `DistributedDataParallel ` will definitely make GRACE more user-friendly. Just like the way we use the horovod version. We are working on this feature. Stay tuned.
