### ISSUE TITLE
About the usage of GRACE 

### ISSUE THREAD

**Issue by Tonyhukaifan** [sands-lab/grace#8]
Is there any way to get and record the communication time between computational nodes? 
I want to get the communication time cost between nodes not include the time cost by the compression algorithm, and also the time cost by the compression algorithm. I couldn't find an appropriate approach to do it.

**Comment by mcanini** [comment]
Currently there is no mechanism to do so within GRACE. We would welcome such a functionality!

In our [technical report](http://hdl.handle.net/10754/662495), we give an estimation of the compression time of various compressors. This was measured as a separate micro-benchmark.
You'd have to add extra instrumentation to perform the kind of measurements you are describing. The horovod profiling facility might also offer additional insights.

**Comment by ChenYuHo** [comment]
Note that communication and computation can overlap.
"Compression" can also overlap with other computation operations such as gradient calculation.
