### ISSUE TITLE
Global or Local compression

### ISSUE THREAD

**Issue by ABukharev** [sands-lab/grace#9]
Dear authors,

I used _issue_ form to submit the general question about the implementation details. The framework works just fine. Thanks, great job! :)

You utilized Horovod's API to construct compression (`Compressor`) and error-feedback (`ResidualMemory`) classes. As far as I know the key methods (compress/ decompress) are applied to the tensors (layers's parameters) **separately** (please correct me if I am wrong). In some cases (_top-k_ compression) the statistics **obtained from all the layers** are required (see https://arxiv.org/pdf/1712.01887.pdf as an example).

The question is next: is it a correct way to apply the compression methods designed to compress the entire update (like _top-k_) to each layer separately?

If it is possible, please, provide your standpoint!

**Comment by ABukharev** [comment]
Please let me know if my question is not clear! I will try to provide a simple example.

**Comment by aritra-dutta** [comment]
Hi Aleksandr, 

Thank you for your question! It was very clear and you are due for a treat! 

Indeed we can point out to you a paper. Please check out recent [AAAI 2020 paper](https://www.aaai.org/ojs/index.php/AAAI/article/view/5793) where we answered the exact question you had in mind, that is, we have provided a detailed insight into the difference between the layer-wise and entire model compression. In this paper, we argue that in light of the present theoretical analysis of compressed SGD in a distributed set-up, the noise incur in a layer-wise compression is bounded above by the noise incur when the same compression is applied to the entire DNN model. That is, one can provide a sharper bound if compression applied in a layer-wise fashion. However, this observation may not always translate into practice. For example, for Top-k compression with small sparsification ratio k and small model sizes, entire model compression outperforms layer-wise compression. 

As you have noticed, in the present theoretical analyses of compressed and communication efficient distributed SGD, the layer-wise artefact is not considered while analyzing the performance of implemented compressor(s). We were the first one to point out the discrepancy! For the full version of our paper with proofs please check our [technical report](http://www.aritradutta.com/uploads/1/1/8/8/118819584/dutta_layerwise_aaai2020.pdf). 

Again many thanks for your interest in our work. Stay in touch. 

Best,
Aritra
